### PR TITLE
f/update-composer-depends

### PR DESCRIPTION
**Pull request by jtyost2**
Updates Config Read to 3.0 version, updates various other dependencies to current CakePHP App 3.x versions as needed.

### CODE REVIEW

**Comment by beporter** [comment]
Shouldn't this change be in `composer.json.template`? Check the last commit for that file: b5e4a69

**Comment by beporter** [comment]
@jtyost2 Did you want to drop `psy/psysh` into both versions of the file?

The idea is that the `composer.json` should include any tools needed to work with and develop the skeleton itself, and the `composer.json.template` should include any tools we want bundled with generated projects out of the box. In at least the latter case, it seems to me like our starting point should be `cakephp/app`s composer.json, although we make some modifications to include stuff like the ConfigReadShell.

**Comment by jtyost2** [comment]
@beporter I don't think so, I think for things like that it makes more sense to drop down to whatever the current version of Cake is requesting?

**Comment by beporter** [comment]
Which includes psysh: https://github.com/cakephp/app/blob/aaa20c03aa4827d583f54941f57799e4b8d678b1/composer.json#L15

**Comment by beporter** [comment]
Remember that `cakephp/cakephp` itself is a "sub" dependency and doesn't include migrations, bake or debugkit:

https://github.com/cakephp/cakephp/blob/c77cdad6f8820399b2ed002887f9f2a028426e38/composer.json#L20

Our skeleton is a sister to `cakephp/app`, and it should mirror it's patterns as closely as possible up until the point that they don't serve our purposes.

**Comment by jtyost2** [comment]
Pushed to add psysh.

**Pull request merged**
