### PR TITLE
Adjusts phpunit.xml paths for Cake 3. Enables clover.xml.

### PR DESCRIPTION
**Pull request by beporter**
This work may still be slightly incomplete on the Shell Scripts end of things, but no harm getting it in here now.

### CODE REVIEW

**Comment by ricog** [comment]
Is it reasonable to put coverage in `/webroot` for easier access? We do this on a few projects already.

**Comment by beporter** [comment]
I would think probably not "by default," since it's a potential security leak to expose the source code to the public like that.

If anything, I'm inclined to suggest we use a wrapper script to move or copy the files in the project where we want that _additional_ behavior of having them public.

There's no harm in "composing" the shell scripts together-- one to generate files in a conventional spot, and another to put them in a custom spot. If we were talking gigabytes of data, we'd probably want to think about a different strategy, but this seems like a good compromise to me. I often do this for the `bin/update` script on servers. I'll create an untracked script that fires bin/update, followed by say `grunt build:staging` (on Fairmount for example) where the stock script is still extremely convenient, but insufficient by itself.

**Comment by ricog** [comment]
The point about security is a good one. I wasn't concerned in staging and production as the entire process is automatic (no chance of coverage being run since phpunit isn't even installed). But it's possible a dev could open their vm web to the public. So I'm no longer interested in moving them. It would be cool if we could output the link, but that's low on the priority list.

**Comment by jtyost2** [comment]
Actually if you have the CakePHP Shell Scripts installed as a `require` dependency, they bundle PHPUnit as a `require` dependency (since some of the scripts require it).

Cake 3 Ref: https://github.com/loadsys/CakePHP-Shell-Scripts/blob/master/composer.json
Cake 2 Ref: https://github.com/loadsys/CakePHP-Shell-Scripts/blob/cake-2.x/composer.json

**Pull request merged**
