### PR TITLE
Check for a files existance before trying to delete

### LINKED ISSUE #73: The Token replacement process needs to fail unlink() gracefully.
Right now, both a `filename.template` **and** a `filename` must exist. If `filename` does not exist, the `unlink()` command to remove it fails and causes the post-create-project-cmd scripts to exit out prematurely:

```
Script App\Console\LoadsysInstaller::postInstall handling the 
post-create-project-cmd event terminated with an exception


                                                                                         
  [ErrorException]                                                                       
  unlink(/Users/beporter/Desktop/newapp/puphpet/config.yaml): No such file or directory  
                                                                                         
```

It must be acceptable for there to **only** be a `filename.template` in the skeleton that will be token-replaced and renamed in the resulting app without a "skeleton-only" equivalent file existing.

### PR DESCRIPTION
**Pull request by alecho**
Should close #73

### CODE REVIEW

**Comment by beporter** [comment]
Can you help me understand why 3 steps (delete original file, copy template file, delete template file) work better, or is safer, or whatever instead of just using [`rename()`](http://php.net/manual/en/function.rename.php) to change the template's name into the original file's name (overwriting the original in the process)?

**Comment by alecho** [comment]
Only because I've read somewhere that on Windows `rename()` may not work as expected. I know Composer has a class with a method for this same thing which might be better to use: https://getcomposer.org/apidoc/master/Composer/Util/Filesystem.html#method_copyThenRemove

**Comment by beporter** [comment]
What's your preference here? Merge it as-is then? Or do you want to make that switch to the composer library command at least?

**Comment by alecho** [comment]
Let's just merge and make another issue?

**Pull request merged**
