### PR TITLE
Change Default Session Implementation To Use Cache

### PR DESCRIPTION
**Pull request by jtyost2**
- [x] Update Sessions Configuration To Use Cache
- [x] Add Session Configuration to the Cache Block, should default to mirror default Cache Configuration
- [x] Edit Session Configuration to Use Session Cache Block
- [x] Add Comments Explaining both where sessions live, how they are cached and how to separate them from normal caching if desired at a later date/time

### CODE REVIEW

**Comment by beporter** [comment]
Does there need to be a special `Cache::config('sessions')` config for that to work? Or does it just use the `default` Cache config?

**Comment by beporter** [comment]
Ah: http://book.cakephp.org/3.0/en/development/sessions.html#cache-sessions

**Comment by beporter** [comment]
So my recommendation would be to add a new, dedicated `sessions` Cache config that (for now) mirrors the default config, and setting up the Sessions config to use it. The thinking here is that if you have a ton of load, it might be possible to overwhelm a "shared" cache + session server and cause sessions to expire prematurely.

Being able to split sessions off to their own server quickly seems like a prudent (if probably unnecessary at our scales) preemptive step.

**Comment by jtyost2** [comment]
Added comments regarding all this

**Pull request merged**
