### PR TITLE
Overhauls readme.

### PR DESCRIPTION
**Pull request by beporter**
Includes a lot more information about how the skeleton works and what each part does.

Explains how the template system works.

I humbly request someone read through the raw version (it's easier than reading the diff) and let me know if they spot anything that needs correction.

### CODE REVIEW

**Comment by ricog** [comment]
Isn't it amazing how great a code diff works, but a readme diff is almost painful.

Looks good. Thank you for writing all this up. A few recommended edits (I can make these if you like).

14: I would recommend removing the extra text from the `composer` bullet in the requirements. It really isn't necessary to install composer globally.

32: The localhost:8080 could be an actual link. Also, #68 and #69 affect what this link would be.

69: Will we still have PEAR dependencies?

85: See #68 and #69, IP needs to change, but there are no port forwards. Also, I haven't seen any value in setting the hostname (it does not conflict anymore), but it probably doesn't hurt to set it to something.

**Comment by beporter** [comment]
No composer doesn't HAVE to be installed globally, but making that an explicit assumption in the skeleton means all composer commands can be written more succinctly, which is appealing. 

The hostname now gets used by vagrant to name the VM in vbox or VMware. These names can not conflict and must still be unique. It also makes it way easier to know what VM you are sshed into when he host name is set properly on your command prompt.

**Comment by ricog** [comment]
My new VM (virtualbox) names look like this even with the hostname set in the first one.
gamingtoday_default_1420742395308_34392
serenity_default_1422455353899_64886

The first part is the folder name.

**Comment by beporter** [comment]
That's because the `vm:hostname:` entry in config.yaml is blank in the default config file. Virtualbox is having to create it's own (pretty ugly) name for you. There are indeed benefits to having a hostname (and a VM name) set, so we typically configure one in our projects. I'm in favor of this bring a __TOKEN__ replacement.

**Comment by beporter** [comment]
The port forwards are pretty necessary if you want to use a single Sequel Pro config to get into **any** of the VMs when they are currently running like I can do now. I'm not enthusiastic about having to create a new connection for each unique VM IP. That sucks; it's more dumb busywork that isn't getting code done for clients. There's got to be a way to make this work for both of our styles.

**Comment by ricog** [comment]
I was doing some research on possible port forward options last night, but haven't found a good solution.

Regarding Sequel Pro, you're talking about a single config for all VMs? That would put us back to having a single VM up at any given time. I'm not sure how that would work for us. I think switching VMs would be terribly inefficient.

For example, if I'm working on Serenity and Andrew has a question on APOBox, I would need to shut down Serenity, open APOBox, answer his question, shut down APOBox , and then start Serenity again.

I'm all for it if we can find an efficient way to switch, but otherwise I'm ok having multiple sequel pro configs. I have different configs for client production and stage servers anyway.

**Comment by beporter** [comment]
Made some updates. Does this look good now?

**Comment by beporter** [comment]
I know the port forwarding stuff is still in the air, but that's going to happen for a while till some of this settles down a bit.

**Comment by jtyost2** [comment]
Re: the `composer` instructions, the prevailing practice in the PHP community is to make the `composer` instructions follow the pattern of `php composer.phar ....` (You can see it in the [CakePHP 3.0 Book](http://book.cakephp.org/3.0/en/quickstart.html)).

Personally though, leave the way it is, since while this is/will be public it in general isn't designed with public consumption in mind.

**Comment by jtyost2** [comment]
Note pushed a commit to update the tokens in the Readme to match PR #76.

**Comment by jtyost2** [comment]
Should the README mention anything about setting up the travis.yml file (Github token, etc)?

**Comment by beporter** [comment]
This is the perfect one time setup thing that a Dev should never have to remember to do themselves. 

If possible, I think we need a post-create-project script that checks for the `travis` command line tool and offers to generate and insert the github token for you. This doesn't need to be a ".template" thing because I think you can get the Travis command to update the file for you now.

I think the only catch is that the Travis conman needs to generate a repo-specific key, which means the newly spawned project will NEED to have a remote configured during setup. I might be remembering the specifics wrong on this, but I do know you can't share encrypted env vars between different .travis.yml files-- they need to be generated for each project. (Maybe the requirement is that travis-ci.com already knows about the project??)

**Comment by beporter** [comment]
I think the only catch is that the Travis conman needs to generate a repo-specific key, which means the newly spawned project might **need** to have a remote configured during setup. I might be remembering the specifics wrong on this, but I do know you can't share encrypted env vars between different .travis.yml files-- they need to be generated for each project. (Maybe the requirement is that travis-ci.com already knows about the project??)

**Comment by jtyost2** [comment]
Far as I can tell the only requirement for encryption is just having the `travis` gem installed.

Ref: http://docs.travis-ci.com/user/encryption-keys/#Usage (copying this to the PR in question)

**Pull request merged**
