### PR TITLE
Pulls the .travis.yml file from the 2.0 Branch

### PR DESCRIPTION
**Pull request by jtyost2**
Pulls the .travis.yml branch from the 2.0 Branch.

There are few issues that have to be resolved for this be totally valid.

Either:

1. The shell scripts need to be updated to reflect Cake 3.0
2. The commands for running the tests and codesniffer needs to be updated in this PR.

In either case the current .travis.yml file is inaccurate for actually testing a Cake app.

### CODE REVIEW

**Comment by beporter** [comment]
I think if it's possible to write simpler commands now with 3.0 that no longer require a shell script to enshrine the correct invocations, we should ditch individual shell scripts wherever possible. If run-tests can be made obsolete, so much the better in my book. 

I don't have a 3.0.x tag published for the shell scripts repo yet anyway, so my vote is to start by rewriting the Travis build commands to work without them for now. We can always re-improve the travis file as the shell scripts catch up to 3.0 land.

**Comment by beporter** [comment]
This may also be a good case where we want a `.travis.yml.template` file separate from a `.travis.yml` file so that we can continue to run code-sniffs (and test the eventual "default code" bundled?) on the skeleton itself, while still providing an appropriate version of the file for fresh projects.

In other words: I like the purpose of the old version of the .travis.yml file (except maybe with our sniffer instead of Cake's). Should we move your imports into a .travis.yml.template file instead? Thoughts?

**Comment by jtyost2** [comment]
I'm in favor of @beporter's suggestion:

A `.travis.yml` file that still runs the skeleton through our Codesniffer
And a new `.travis.yml.template` for new projects.

**Comment by jtyost2** [comment]
Ref: https://github.com/loadsys/CakePHP-Skeleton/pull/78#issuecomment-72314986

Yeah, that's a reasonable statement to rebuild the `.travis.yml` commands from the ground up given that most of the shell scripts would be void.

**Comment by jtyost2** [comment]
I'm making a note and assigning this to myself to mess with.

**Comment by beporter** [comment]
Current plan is to use the EU Rebuild as a test bed for making any additional necessary corrections, then backport those fixes into the skeleton.

**Pull request closed without merging**
