### PR TITLE
Finish config changes from #53

### PR DESCRIPTION
**Pull request by ricog**
This PR completes the necessary changes mentioned in #53.

### CODE REVIEW

**Comment by beporter** [comment]
I humbly object to repeating the `env('APP_ENV')` call multiple times. :disappointed: The nice thing about the way that the 2.x skeleton handled this is that literally your whole app could toggle it's configuration based on a single line of code. If you needed to rely on a hostname or something else as the switch, it was set in a single place, even in this small chunk of code. I think that's one of the "beautiful" parts of this approach, and something I was intending to highlight in my CakeFest talk. Here's the 2.x code I'm talking about, for reference:

```php
$env = getenv('APP_ENV');
if (is_readable(dirname(__FILE__) . "/core-{$env}.php")) {
	Configure::load("core-{$env}");
}
if (is_readable(dirname(__FILE__) . '/core-local.php')) {
	Configure::load('core-local');
}
```

**Comment by ricog** [comment]
I agree, `env('APP_ENV')` should only be used in this one spot (while actually loading the environment specific config). From there on out, the code should rely on the configuration. However, I don't see an advantage of assigning it to `$env` here. `$env` shouldn't be used anywhere else, right?

**Comment by beporter** [comment]
If you want to change from an `env()` var to a `$_SERVER` var (or something else), you have to remember to change it three times for the code to continue to work correctly.

If you want to change the name of the env var you look up from `APP_ENV` to something else, you have to remember to change it three times for the code to continue to work correctly.

`$env` isn't used anywhere else, that's not the point. It's only needed in the immediately following two lines. It just isn't DRY the way it's written now, is all.

**Comment by beporter** [comment]
I mean, throw an `unset($env)` at the bottom, if that's the issue.

**Pull request merged**
