### PR TITLE
Add a new [App]Table class with stubbed tests.

### LINKED ISSUE #135: Import AppTable work from EU Mk2.
https://github.com/loadsys/EducationUnlimited-Mk2/commit/df812f5468dfedcf033a25aad7a6d7c1fc35ec76

This needs to be paired with bake template changes in our LoadsysTheme so that new Tables inherit from `\App\Model\Table\Table` instead of `\Cake\ORM\Table` by default, and so `initialize()`, `validationDefault()` and `buildRules()` call their parents by default too (which will have zero effect on those projects choosing not to use this feature, just like Cake 2.)

### PR DESCRIPTION
**Pull request by beporter**
TODO before merging:

* [x] Update LoadsysTheme to bake Tables that inherit from the new `App/Model/Table/Table.php` class. loadsys/CakePHP-LoadsysTheme#15
* [x] Rip CreatorModifier Behavior out of EU into a plugin, publish to composer. loadsys/CakePHP-CreatorModifier#1
* [x] Include `"loadsys/cakephp-creatormodififer": "~3.0",` in `composer.json` in this PR once available.

Closes #135.

### CODE REVIEW

**Comment by beporter** [comment]
This PR has a lot of external dependencies (listed above) which should all be ready to test now. It'd probably be a good idea for someone (other than me) to run a `composer create-project` against this branch, load the DB with a sample table (suggestion below), bake a stack and make sure the AppTable, CreatorModifier, tests and codesniffs all work top to bottom.


```sql
CREATE TABLE `camp_sessions` (
  `id` char(36) NOT NULL,
  `name` varchar(255) NOT NULL,
  `start_date` date NOT NULL,
  `end_date` date NOT NULL,
  `prototype_price` decimal(10,2) NOT NULL DEFAULT '0.00',
  `created` datetime DEFAULT NULL,
  `creator_id` char(36) DEFAULT NULL,
  `modified` datetime DEFAULT NULL,
  `modifier_id` char(36) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

**Comment by jtyost2** [comment]
The test tokens still exist.
screen shot 2015-07-22 at 9 50 04 am

**Comment by beporter** [comment]
Yep, that's documented in #72 already.

**Comment by beporter** [comment]
Seems good (enough). Merging.

**Pull request merged**
